In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

In [3]:
#%cd /content/projetofase2flammers

In [4]:
#!git pull

In [ ]:
#!pip install streamlit

Defaulting to user installation because normal site-packages is not writeable
Collecting streamlit
  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.2.2-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.1.4-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (8.3.1)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy<3,>=1.23 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (2.4.3)
Requirement already satisfied: packaging>=20 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (3.0.1)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (12.1.1)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting protobuf<8,>=3.20 (from streamlit)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (1.0.0)
Requirement already satisfied: uvicorn>=0.30.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (0.42.0)
Collecting httptools>=0.6.3 (from streamlit)
  Downloading httptools-0.8.0-cp314-cp314-win_amd64.whl.metadata (3.7 kB)
Requirement already satisfied: anyio>=4.0.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from streamlit) (4.12.1)
Collecting python-multipart>=0.0.10 (from streamlit)
  Downloading python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets>=12.0.0 (from streamlit)
  Using cached websockets-16.0-cp314-cp314-win_amd64.whl.metadata (7.0 kB)
Collecting itsdangerous>=2.1.2 (from streamlit)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: jinja2 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Collecting narwhals>=2.4.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: colorama in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.27->streamlit) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in C:\Users\Teste\AppData\Roaming\Python\Python314\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.2 MB 2.5 MB/s eta 0:00:04
   ---- ----------------------------------- 1.0/9.2 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.2 MB 2.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.1/9.2 MB 2.7 MB/s eta 0:00:03
   ----------- ---------------------------- 2.6/9.2 MB 2.7 MB/s eta 0:00:03
   -------------- ------------------------- 3.4/9.2 MB 2.7 MB/s eta 0:00:03
   ----------------- ---------------------- 3.9/9.2 MB 2.7 MB/s eta 0:00:02
   ------------------- -------------------- 4.5/9.2 MB 2.7 MB/s eta 0:00:02
   --------------------- ------------------ 5.0/9.2 MB 2.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.5/9.2 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 5.8/9.2 MB 2.6 MB/s eta 0:00:02
   --------------------------- ------------ 6.3/9.2 MB 2.5 MB/s eta 0:00:02
   ------------------------------ --------- 7.1/9.2 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 7.6/9.2 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 8.1/9.2 MB 2.6 MB/s eta 0:00:01
   ------------------------------------- -- 8.7/9.2 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.2 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 9.2/9.2 MB 2.6 MB/s  0:00:03
Downloading altair-6.2.2-py3-none-any.whl (797 kB)
   ---------------------------------------- 0.0/797.6 kB ? eta -:--:--
   -------------------------- ------------- 524.3/797.6 kB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 797.6/797.6 kB 3.0 MB/s  0:00:00
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-7.1.4-py3-none-any.whl (16 kB)
Downloading gitpython-3.1.50-py3-none-any.whl (212 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.3 MB 2.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/11.3 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/11.3 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.3 MB 2.5 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.3 MB 2.6 MB/s eta 0:00:04
   ------------ --------------------------- 3.4/11.3 MB 2.7 MB/s eta 0:00:03
   ------------- -------------------------- 3.9/11.3 MB 2.7 MB/s eta 0:00:03
   ---------------- ----------------------- 4.7/11.3 MB 2.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.3 MB 2.7 MB/s eta 0:00:03
   ------------------ --------------------- 5.2/11.3 MB 2.6 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.3 MB 2.5 MB/s eta 0:00:03
   ---------------------- ----------------- 6.3/11.3 MB 2.5 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.3 MB 2.5 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.3 MB 2.5 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.3 MB 2.4 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.3 MB 2.3 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.3 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 8.7/11.3 MB 2.3 MB/s eta 0:00:02
   ------------------------------- -------- 8.9/11.3 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 9.4/11.3 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.3 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 10.7/11.3 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.3 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 2.2 MB/s  0:00:05
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading httptools-0.8.0-cp314-cp314-win_amd64.whl (92 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl (28.0 MB)
   ---------------------------------------- 0.0/28.0 MB ? eta -:--:--
    --------------------------------------- 0.5/28.0 MB 2.7 MB/s eta 0:00:11
   - -------------------------------------- 1.0/28.0 MB 2.4 MB/s eta 0:00:12
   -- ------------------------------------- 1.8/28.0 MB 2.8 MB/s eta 0:00:10
   --- ------------------------------------ 2.4/28.0 MB 2.9 MB/s eta 0:00:09
   --- ------------------------------------ 2.6/28.0 MB 2.7 MB/s eta 0:00:10
   ---- ----------------------------------- 3.1/28.0 MB 2.5 MB/s eta 0:00:11
   ---- ----------------------------------- 3.4/28.0 MB 2.5 MB/s eta 0:00:10
   ----- ---------------------------------- 3.9/28.0 MB 2.4 MB/s eta 0:00:11
   ------ --------------------------------- 4.5/28.0 MB 2.4 MB/s eta 0:00:11
   ------- -------------------------------- 5.0/28.0 MB 2.4 MB/s eta 0:00:10
   ------- -------------------------------- 5.5/28.0 MB 2.4 MB/s eta 0:00:10
   -------- ------------------------------- 6.0/28.0 MB 2.4 MB/s eta 0:00:10
   --------- ------------------------------ 6.6/28.0 MB 2.4 MB/s eta 0:00:09
   --------- ------------------------------ 6.8/28.0 MB 2.4 MB/s eta 0:00:10
   ---------- ----------------------------- 7.3/28.0 MB 2.3 MB/s eta 0:00:09
   ----------- ---------------------------- 7.9/28.0 MB 2.3 MB/s eta 0:00:09
   ----------- ---------------------------- 7.9/28.0 MB 2.3 MB/s eta 0:00:09
   ----------- ---------------------------- 8.4/28.0 MB 2.3 MB/s eta 0:00:09
   ------------ --------------------------- 8.9/28.0 MB 2.3 MB/s eta 0:00:09
   ------------- -------------------------- 9.4/28.0 MB 2.3 MB/s eta 0:00:09
   -------------- ------------------------- 10.0/28.0 MB 2.3 MB/s eta 0:00:08
   -------------- ------------------------- 10.5/28.0 MB 2.3 MB/s eta 0:00:08
   ---------------- ----------------------- 11.3/28.0 MB 2.3 MB/s eta 0:00:08
   ---------------- ----------------------- 11.8/28.0 MB 2.3 MB/s eta 0:00:07
   ----------------- ---------------------- 12.3/28.0 MB 2.4 MB/s eta 0:00:07
   ------------------ --------------------- 12.8/28.0 MB 2.4 MB/s eta 0:00:07
   ------------------- -------------------- 13.4/28.0 MB 2.4 MB/s eta 0:00:07
   ------------------- -------------------- 13.9/28.0 MB 2.4 MB/s eta 0:00:06
   -------------------- ------------------- 14.4/28.0 MB 2.4 MB/s eta 0:00:06
   --------------------- ------------------ 15.2/28.0 MB 2.4 MB/s eta 0:00:06
   ---------------------- ----------------- 15.7/28.0 MB 2.4 MB/s eta 0:00:06
   ----------------------- ---------------- 16.3/28.0 MB 2.4 MB/s eta 0:00:05
   ----------------------- ---------------- 16.8/28.0 MB 2.4 MB/s eta 0:00:05
   ------------------------ --------------- 17.0/28.0 MB 2.4 MB/s eta 0:00:05
   ------------------------- -------------- 17.6/28.0 MB 2.4 MB/s eta 0:00:05
   -------------------------- ------------- 18.4/28.0 MB 2.4 MB/s eta 0:00:05
   -------------------------- ------------- 18.9/28.0 MB 2.4 MB/s eta 0:00:04
   ---------------------------- ----------- 19.7/28.0 MB 2.4 MB/s eta 0:00:04
   ---------------------------- ----------- 20.2/28.0 MB 2.4 MB/s eta 0:00:04
   ----------------------------- ---------- 20.4/28.0 MB 2.4 MB/s eta 0:00:04
   ----------------------------- ---------- 21.0/28.0 MB 2.4 MB/s eta 0:00:03
   ------------------------------ --------- 21.2/28.0 MB 2.4 MB/s eta 0:00:03
   ------------------------------- -------- 21.8/28.0 MB 2.4 MB/s eta 0:00:03
   ------------------------------- -------- 22.3/28.0 MB 2.4 MB/s eta 0:00:03
   -------------------------------- ------- 22.8/28.0 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 23.6/28.0 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 23.9/28.0 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 24.4/28.0 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 25.2/28.0 MB 2.4 MB/s eta 0:00:02
   ------------------------------------ --- 25.7/28.0 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 26.2/28.0 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 27.0/28.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  27.5/28.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 28.0/28.0 MB 2.5 MB/s  0:00:11
Downloading python_multipart-0.0.32-py3-none-any.whl (30 kB)
Using cached websockets-16.0-cp314-cp314-win_amd64.whl (178 kB)
Installing collected packages: websockets, watchdog, toml, tenacity, smmap, python-multipart, pyarrow, protobuf, narwhals, itsdangerous, httptools, cachetools, blinker, pydeck, gitdb, gitpython, altair, streamlit

   ----------------------------------------  0/18 [websockets]
   ---- -----------------------------------  2/18 [toml]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   ------------- --------------------------  6/18 [pyarrow]
   --------------- ------------------------  7/18 [protobuf]
   --------------- ------------------------  7/18 [protobuf]
   ----------------- ----------------------  8/18 [narwhals]
   ----------------- ----------------------  8/18 [narwhals]
   ----------------- ----------------------  8/18 [narwhals]
   ----------------- ----------------------  8/18 [narwhals]
   -------------------- -------------------  9/18 [itsdangerous]
   ---------------------------- ----------- 13/18 [pydeck]
   ------------------------------- -------- 14/18 [gitdb]
   --------------------------------- ------ 15/18 [gitpython]
   ----------------------------------- ---- 16/18 [altair]
   ----------------------------------- ---- 16/18 [altair]
   ----------------------------------- ---- 16/18 [altair]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ------------------------------------- -- 17/18 [streamlit]
   ---------------------------------------- 18/18 [streamlit]

Successfully installed altair-6.2.2 blinker-1.9.0 cachetools-7.1.4 gitdb-4.0.12 gitpython-3.1.50 httptools-0.8.0 itsdangerous-2.2.0 narwhals-2.22.1 protobuf-7.35.1 pyarrow-24.0.0 pydeck-0.9.2 python-multipart-0.0.32 smmap-5.0.3 streamlit-1.58.0 tenacity-9.1.4 toml-0.10.2 watchdog-6.0.0 websockets-16.0

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd

# 1. Carrega os dois CSVs
hospitais = pd.read_csv('hospitais_df.csv')
pacientes = pd.read_csv('pacientes_df.csv')

# 2. Filtra os pacientes que ainda precisam de atendimento
pacientes_pendentes = pacientes[pacientes['status'] == 'pendente']

# 3. Hospital de Base como ponto de partida (Depósito central = Índice 0)
deposito = hospitais[hospitais['id_hospital'] == 'HBB']

ModuleNotFoundError: No module named 'pandas'

In [ ]:
hospitais.shape
pacientes.shape

(1000, 12)

In [ ]:
pacientes.head()

,id_paciente,nome_ficticio,regiao_administrativa,latitude,longitude,tipo_atendimento,prioridade,janela_inicio,janela_fim,demanda_caixas,temperatura_controlada,status
0,1,Paciente_4447,Gama,-16.009042,-48.055217,emergencia_obstetrica,1,0,24,1,False,pendente
1,2,Paciente_7005,Plano Piloto,-15.799537,-47.942825,pos_parto,4,14,18,2,False,pendente
2,3,Paciente_6286,Ceilândia,-15.823223,-48.090508,pos_parto,4,14,18,2,False,pendente
3,4,Paciente_9805,Plano Piloto,-15.806678,-47.976268,violencia_domestica,2,0,24,2,False,pendente
4,5,Paciente_2472,Samambaia,-15.904855,-48.048246,pos_parto,4,14,18,1,False,pendente

In [ ]:
hospitais.head()

  id_hospital                             nome  latitude  longitude
0         HBB  Hospital de Base (Plano Piloto)  -15.7984   -47.8864
1         HRC   Hospital Regional de Ceilândia  -15.8239   -48.1152
2         HRT  Hospital Regional de Taguatinga  -15.8335   -48.0628
3       HRSAM   Hospital Regional de Samambaia  -15.8741   -48.0848

In [ ]:

import pandas as pd
import streamlit as st

# 1. Carrega o CSV gerado
df_pacientes = pd.read_csv('pacientes_df.csv')

# 2. Conta a quantidade de pacientes por Região Administrativa
contagem_por_regiao = df_pacientes['regiao_administrativa'].value_counts()

# Mostra no console (Terminal)
print(contagem_por_regiao)

# Mostra no Streamlit (Interface Web)
st.bar_chart(contagem_por_regiao)

2026-06-29 13:31:36.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-29 13:31:36.509 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-29 13:31:36.510 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

regiao_administrativa
Samambaia       224
Taguatinga      206
Gama            195
Plano Piloto    194
Ceilândia       181
Name: count, dtype: int64

DeltaGenerator()