<a href="https://colab.research.google.com/github/Flamers-Team/projetofase2flammers/blob/main/projetofase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
# 1. Garanta que o Colab está dentro da pasta do seu projeto
%cd /content/projetofase2flammers

/content/projetofase2flammers

In [2]:
!git pull

Already up to date.

In [3]:
import pandas as pd

# 1. Carrega os dois CSVs
hospitais = pd.read_csv('hospitais_df.csv')
pacientes = pd.read_csv('pacientes_df.csv')

# 2. Filtra os pacientes que ainda precisam de atendimento
pacientes_pendentes = pacientes[pacientes['status'] == 'pendente']

# 3. Hospital de Base como ponto de partida (Depósito central = Índice 0)
deposito = hospitais[hospitais['id_hospital'] == 'HBB']

In [4]:
hospitais.shape
pacientes.shape

(1000, 12)

In [5]:
pacientes.head()

,id_paciente,nome_ficticio,regiao_administrativa,latitude,longitude,tipo_atendimento,prioridade,janela_inicio,janela_fim,demanda_caixas,temperatura_controlada,status
0,1,Paciente_4447,Gama,-16.009042,-48.055217,emergencia_obstetrica,1,0,24,1,False,pendente
1,2,Paciente_7005,Plano Piloto,-15.799537,-47.942825,pos_parto,4,14,18,2,False,pendente
2,3,Paciente_6286,Ceilândia,-15.823223,-48.090508,pos_parto,4,14,18,2,False,pendente
3,4,Paciente_9805,Plano Piloto,-15.806678,-47.976268,violencia_domestica,2,0,24,2,False,pendente
4,5,Paciente_2472,Samambaia,-15.904855,-48.048246,pos_parto,4,14,18,1,False,pendente

In [6]:
hospitais.head()

  id_hospital                             nome  latitude  longitude
0         HBB  Hospital de Base (Plano Piloto)  -15.7984   -47.8864
1         HRC   Hospital Regional de Ceilândia  -15.8239   -48.1152
2         HRT  Hospital Regional de Taguatinga  -15.8335   -48.0628
3       HRSAM   Hospital Regional de Samambaia  -15.8741   -48.0848